### ISSUE TITLE
requirements.txt is incomplete 

### ISSUE THREAD

**Issue by SanazKaz** [jinghanzhang1998/RATT#2]
Please specify versions used of the packages in requirements.txt for RATT 

pip3 freeze > requirements.txt  # Python3
 https://stackoverflow.com/questions/31684375/automatically-create-file-requirements-txt

(it appears the previous issue i opened is in relation to package updates/ deprecations!)

Many thanks for your help

**Comment by jinghanzhang1998** [comment]
Hello Sanaz,

Could you please perform a quick check for me?

I would like to confirm if running the offline version of our code,
RATT_creative_writing_offline.ipynb, without installing the packages
listed in requirements.txt, would result in any errors. The
dependencies for this notebook are different and are intended to be
installed directly within the notebook using the following commands:
```
!pip install -U llama_hub llama_index braintrust autoevals pypdf
pillow transformers llama-index-embeddings-huggingface
pip install unstructured==0.5.6
```
These dependencies might conflict with those listed in
requirements.txt, which was tailored for example_creative_writing.py.
I think
this could be the reason that you cannot run the code as we expected.


Jinghan

**Comment by SanazKaz** [comment]
Dear Jinghan,

Many thanks for your reply, i will have a go again; the previous issue i opened is what happens when i just run the notebook. 

I will run the notebook in a new environment on its own and see if it works, if it does i will close the issues!

All the best :)

**Comment by SanazKaz** [comment]
Dear Jinghan,

 I created a new envrionment and tried to run the creative writing notebook but i am encountering the issue i opened in issue 1. 

I will leave it with you. Perhaps it is a Mac Silicon issue?  - the error is as follows for the notebook.

Number of Agents: 3
Number of Steps: 3
Final Output Mode: only_last_step
2024-07-12 11:42:17.974183 [INFO] Retrieving Step 1 draft...
huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
	- Avoid using `tokenizers` before the fork if possible
	- Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)
2024-07-12 11:42:26.125677 [INFO] Processing draft...
2024-07-12 11:42:26.125882 [INFO] Draft split into 11 parts
================================================================================
2024-07-12 11:42:26.125906 [INFO] Processing part 1/11...
2024-07-12 11:42:26.125914 [INFO] Generating corresponding query...
2024-07-12 11:42:26.274848 [INFO] Function <function get_query_wrapper at 0x37169ef80> completed successfully
huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
	- Avoid using `tokenizers` before the fork if possible
	- Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Users/sanazkazeminia/anaconda3/envs/ratt_env/lib/python3.10/multiprocessing/spawn.py", line 116, in spawn_main
    exitcode = _main(fd, parent_sentinel)
  File "/Users/sanazkazeminia/anaconda3/envs/ratt_env/lib/python3.10/multiprocessing/spawn.py", line 126, in _main
    self = reduction.pickle.load(from_parent)
AttributeError: Can't get attribute 'get_query_wrapper' on <module '__main__' (built-in)>
---------------------------------------------------------------------------
KeyboardInterrupt                         Traceback (most recent call last)
Cell In[17], [line 400](vscode-notebook-cell:?execution_count=17&line=400)
    [397](vscode-notebook-cell:?execution_count=17&line=397) print("Number of Steps:", num_steps)
    [398](vscode-notebook-cell:?execution_count=17&line=398) print("Final Output Mode:", final_output_mode)
--> [400](vscode-notebook-cell:?execution_count=17&line=400) answer_cot, answer_ratt = ratt("Introduce safety finetuning.")

Cell In[17], [line 334](vscode-notebook-cell:?execution_count=17&line=334)
    [332](vscode-notebook-cell:?execution_count=17&line=332) step_num = num_steps
    [333](vscode-notebook-cell:?execution_count=17&line=333) print(f"{datetime.now()} [INFO] Retrieving Step 1 draft...")
--> [334](vscode-notebook-cell:?execution_count=17&line=334) draft = get_draft_tot_inital(question,num_agents)
    [335](vscode-notebook-cell:?execution_count=17&line=335) print(f"{datetime.now()} [INFO] Step 1 draft returned")
    [336](vscode-notebook-cell:?execution_count=17&line=336) print(f"##################### DRAFT #######################")

Cell In[17], [line 196](vscode-notebook-cell:?execution_count=17&line=196)
    [193](vscode-notebook-cell:?execution_count=17&line=193) print(f"{datetime.now()} [INFO] Draft split into {len(draft_paragraphs)} parts")
    [195](vscode-notebook-cell:?execution_count=17&line=195) # Modify using RAG
--> [196](vscode-notebook-cell:?execution_count=17&line=196) draft_modified = RAG(question, draft_paragraphs)
    [198](vscode-notebook-cell:?execution_count=17&line=198) # Add each generated draft to the list
    [199](vscode-notebook-cell:?execution_count=17&line=199) agents_drafts.append(f"Agent{i+1}: {draft_modified}")

Cell In[17], [line 95](vscode-notebook-cell:?execution_count=17&line=95)
     [92](vscode-notebook-cell:?execution_count=17&line=92) answer += '\n\n' + p
     [94](vscode-notebook-cell:?execution_count=17&line=94) print(f"{datetime.now()} [INFO] Generating corresponding query...")
---> [95](vscode-notebook-cell:?execution_count=17&line=95) res = run_with_timeout(get_query_wrapper, 3, question, answer)
...
--> [379](https://file+.vscode-resource.vscode-cdn.net/Users/sanazkazeminia/Downloads/RATT-main/~/anaconda3/envs/ratt_env/lib/python3.10/multiprocessing/connection.py:379)     chunk = read(handle, remaining)
    [380](https://file+.vscode-resource.vscode-cdn.net/Users/sanazkazeminia/Downloads/RATT-main/~/anaconda3/envs/ratt_env/lib/python3.10/multiprocessing/connection.py:380)     n = len(chunk)
    [381](https://file+.vscode-resource.vscode-cdn.net/Users/sanazkazeminia/Downloads/RATT-main/~/anaconda3/envs/ratt_env/lib/python3.10/multiprocessing/connection.py:381)     if n == 0:

KeyboardInterrupt:

**Comment by XinhaoZh23** [comment]
Although it is unclear what is causing the difference in environment variable settings, based on the error message you provided, you might try setting the environment variable `TOKENIZERS_PARALLELISM` to `false` to disable tokenizer parallelism explicitly:


import os
os.environ["TOKENIZERS_PARALLELISM"] = "false"


This might solve your problem.

**Comment by SanazKaz** [comment]
Hi all, the error was occurring as llama index has deprecated service context  - please see here https://docs.llamaindex.ai/en/stable/module_guides/supporting_modules/service_context_migration/ once I changed the code, it ran smoothly.

**Comment by XinhaoZh23** [comment]
Thank you for your diligent follow-up. If there are any further issues, please let us know.
